name: client_001
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  geolocator: ^13.0.1
  url_launcher: ^6.3.1
  convex_bottom_bar: ^3.2.0
  ultralytics_yolo: ^0.0.3
  shared_preferences: ^2.2.3
  get: ^4.6.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
